# Generated by Django 3.2.5 on 2021-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=350)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
