# Generated by Django 3.2.5 on 2021-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
