# Generated by Django 3.2.5 on 2021-08-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210817_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
