# Generated by Django 3.2.5 on 2021-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='allIps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.TextField(default=None)),
            ],
        ),
    ]
