# Generated by Django 3.2.5 on 2021-08-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_allips'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ips',
            field=models.TextField(default=None),
        ),
    ]
