# Generated by Django 3.2.5 on 2021-08-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ips',
        ),
    ]
