# Generated by Django 3.2.5 on 2021-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ips',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateField(blank=True),
        ),
    ]
