# Generated by Django 3.2.5 on 2021-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_post_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='allips',
            name='postname',
            field=models.TextField(default=None),
        ),
    ]
