# Generated by Django 3.2.5 on 2021-08-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_allips_postname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allips',
            name='ips',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='allips',
            name='postname',
            field=models.TextField(blank=True, default=None),
        ),
    ]
