# Generated by Django 3.2.5 on 2021-08-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210818_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allips',
            name='postname',
        ),
        migrations.AlterField(
            model_name='allips',
            name='ips',
            field=models.TextField(default=None),
        ),
    ]
