# Generated by Django 3.2.5 on 2021-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210818_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='allips',
            name='postname',
            field=models.TextField(default=None),
        ),
    ]
